"""Create User Table

Revision ID: 7b4aed9402a8
Revises: 47cabd4212ac
Create Date: 2024-08-17 20:54:57.627157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4aed9402a8'
down_revision: Union[str, None] = '47cabd4212ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('username', sa.String(length=12), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
